"""add full name column to user model

Revision ID: ae3485e0f67a
Revises: b73c68bd2145
Create Date: 2026-06-11 09:04:56.565564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3485e0f67a'
down_revision: Union[str, Sequence[str], None] = 'b73c68bd2145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
