"""Deleteing unique=True from category_id in the product model

Revision ID: b73c68bd2145
Revises: cb6a985391b9
Create Date: 2026-06-11 09:00:42.944063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73c68bd2145'
down_revision: Union[str, Sequence[str], None] = 'cb6a985391b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_category_id_key'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('products_category_id_key'), 'products', ['category_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
