"""Initial

Revision ID: cb6a985391b9
Revises: 
Create Date: 2026-06-11 08:57:17.706559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6a985391b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('categories_product_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'product_id')
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'products', ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('categories', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_product_id_fkey'), 'categories', 'products', ['product_id'], ['id'])
    op.alter_column('categories', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
