"""Make full name mandatory to fill

Revision ID: f6f84d208339
Revises: ae3485e0f67a
Create Date: 2026-06-11 09:05:56.970888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f84d208339'
down_revision: Union[str, Sequence[str], None] = 'ae3485e0f67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    UPDATE users
    SET email = username || '@placeholder.local'
    WHERE email IS NULL
    """)

    op.alter_column('users', 'email', existing_type=sa.VARCHAR(), nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
